### ISSUE TITLE
Improve output from wipe command

### ISSUE THREAD

**Issue by jdknives** [skycoin/hardware-wallet-go#10]
OS: MacOS 10.14.6
Firmware:1.0.0

Problem:

When running the wipe command on a connected Skywallet in regular mode, the command returns 

`Device wiped` 

and the Skywallet actually ask for confirmation. However, the device needs to be in bootloader mode for the firmware to actually be wiped. Otherwise it will remain on the device. 

Expected behaviour:

An unsuccessful `wipe` should suggest in the output, that the device needs to be in bootloader mode for this to work.

**Comment by Midren** [comment]
@jdknives In bootloader mode and in the regular mode we have two message handlers. In regular mode, it wipes data from [storage](https://github.com/SkycoinProject/hardware-wallet/blob/develop/tiny-firmware/firmware/fsm_impl.c#L423) (pin, seed, resets entropy mixer). In bootloader mode, it erases completely [firmware](https://github.com/SkycoinProject/hardware-wallet/blob/develop/tiny-firmware/bootloader/usb.c#L369).

We can change hardware-wallet-go, so it will first send getFeatures msg and discover if it is in bootloader mode or in the regular, and then write a specific message for a user (e.g. `Firmware was wiped from the device`, `User data was wiped from the device`)

**Comment by jdknives** [comment]
Alright. That would make sense imo. But non-critical right now.

**Comment by Midren** [comment]
@jdknives wipe command after successful wipe just prints the message, that had come from the device. So we can just change the message in hardware-wallet and no changes will be required in hardware-wallet-go (There is no need to do one more call getFeatures). However, in the bootloader, there is no message specified and make a new version of the bootloader because of the response message is not so good idea, so I have just the if statement, that if a message is zero-length, then it should have come from the bootloader mode and so we print `Firmware was wiped from the device`, otherwise, we just print the message, that had come from the device.
