### ISSUE TITLE
Connected always returns false if called separately

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-go#107]
**Describe the bug**
https://github.com/skycoin/hardware-wallet-go/blob/2005503ec26b8ebce4d1edac4bb5c0683e4fcf80/src/device-wallet/device-wallet.go#L432-L435

if `Connected` is called from outside one of the function implementations it will always return false because there is no `d.Connect` call.

**Steps to Reproduce**

1. Connect wallet
2. use hw-daemon to call the `/connected` endpoint
3. returns false even though the device is connected

**Actual behavior**
returns false when device is connected

**Expected behavior**
Return true when device is connected

**Comment by therealssj** [comment]
this is related to https://github.com/skycoin/hardware-wallet-daemon/issues/44

**Comment by stdevAlDen** [comment]
@therealssj I'm not sure that this is the desired approach, since, in my opinion, a **plugged in** device is not the same as a **connected** device, that is, having an Ethernet wire plugged in does not mean that I'm connected to Github server, having plugged in my USB flash memory does not mean that I have this connected(maybe mounted is a better term for `*nix` users), the same concept can be applied for the hw. Maybe I can feel more comfortable with a simple function name change `Connected` -> `CheckIfDeviceIsConnectedOrTryToConnectIfItSNot` This kind of multipart function names warn me up about multiple functions(to keep things simple), and I think these are `Connect`/`Connected` functions pair where `Connected` says if you made a previous call to `Connect` with a successful response and this still valid. Just consider my comment, but, of course, I could be wrong.
